image: ubuntu:latest
before_script:
  - apt update
  - apt install -y wget
  - apt install -y nodejs npm
  - npm install postcss-cli
  - npm install -g n
  - n stable  # 或者 n <version>，根据 Hugo 的要求选择合适的 Node.js 版本
  - wget https://github.com/gohugoio/hugo/releases/download/v0.123.7/hugo_extended_0.123.7_Linux-64bit.tar.gz
  # Extract Hugo binary
  - tar -zxvf hugo_extended_0.123.7_Linux-64bit.tar.gz
  # Move Hugo binary to a directory in PATH
  - mv hugo /usr/local/bin/
  # Verify Hugo installation
  - hugo version
  - apt install -y python3 python3-pip
  - pip3 install awscli
  - aws --version 
  - apt install -y golang
  - go version
  # create a new aws secret key

  - aws configure set default.region us-east-1
  - aws configure list
stages:          # List of stages for jobs, and their order of execution
  - build
  - test
  - deploy
build-job:       # This job runs in the build stage, which runs first.
  stage: build
  script:
 
    - echo "Compiling the code..."
    - echo "Compile complete."
deploy-job:      # This job runs in the deploy stage.
  stage: deploy  # It only runs when *both* jobs in the test stage complete successfully.
  environment: production
  script:
    - echo "Deploying application..."
    - chmod +x publish.sh  # 添加执行权限
    - hugo
    - aws s3 sync public/ s3://mutian-ling.net --acl public-read
    - aws s3 website s3://mutian-ling.net --index-document index.html --error-document 404.html
    - echo "Application successfully deployed."
  only:
    - main

  variables:
    AWS_ACCESS_KEY_ID: "$AWS_ACCESS_KEY_ID"
    AWS_SECRET_ACCESS_KEY: "$AWS_SECRET_ACCESS_KEY"
